# -*- coding: utf-8 -*-
"""PPO_Intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5xRmMex7irLTQJOC7HDHQM2LR7smJI0
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q "gymnasium[mujoco]" stable-baselines3

import gymnasium as gym
import mujoco
import stable_baselines3

print("Gymnasium:", gym.__version__)
print("MuJoCo:", mujoco.__version__)
print("Stable-Baselines3:", stable_baselines3.__version__)

env = gym.make("Reacher-v5")

print("Observation space:", env.observation_space)
print("Action space:", env.action_space)

print("Observation size:", env.observation_space.shape)
print("Action size:", env.action_space.shape)

observation, info = env.reset(seed=42)

print('observation:', observation)
print('number of values:', len(observation))

from os import truncate
action = env.action_space.sample()

next_observation, reward, terminated, truncated, info = env.step(action)

print('Action:', action)
print('Reward:', reward)
print('Terminated:', terminated)
print('Truncated:', truncated)
print('Next observation:', next_observation)

observation, info = env.reset(seed=42)

total_reward = 0
steps = 0
done = False

while not done:
  action = env.action_space.sample()

  observation, reward, terminated, truncated, info = env.step(action)

  total_reward += reward
  steps += 1

  done = terminated or truncated

print('Total reward:', total_reward)
print('Steps:', steps)

import numpy as np

episode_rewards = []

for episode in range(10):
  observation, info = env.reset(seed = episode)
  env.action_space.seed(episode)

  total_reward = 0
  done = False

  while not done:
    action = env.action_space.sample()

    observation, reward, terminated, truncated, info = env.step(action)

    total_reward += reward

    done = terminated or truncated

  episode_rewards.append(total_reward)

print('Episode rewards:', episode_rewards)
print('Mean reward:', np.mean(episode_rewards))

from stable_baselines3 import PPO

train_env = gym.make('Reacher-v5')

model = PPO(
    policy='MlpPolicy',
    env = train_env,
    verbose=1,
    device='cpu'
)

print('PPO agent created')

model.learn(total_timesteps=100_000)
print('training finished')

#Don't need to know this it's just saving model to google drive

from google.colab import drive
import os

drive.mount("/content/drive")

model_folder = "/content/drive/MyDrive/PPO_Robotics_Intro"
os.makedirs(model_folder, exist_ok=True)

model.save(f"{model_folder}/ppo_reacher_day2")

print("Model saved")

demo_env = gym.make("Reacher-v5")

observation, info = demo_env.reset(seed=42)

action, _ = model.predict(
    observation,
    deterministic=True
)

next_observation, reward, terminated, truncated, info = demo_env.step(action)

print("PPO action:", action)
print("Reward:", reward)
print("Next observation:", next_observation)

eval_env = gym.make('Reacher-v5')

ppo_rewards = []

for episode in range(10):
    observation, info = eval_env.reset(seed=episode)

    total_reward = 0
    done = False

    while not done:
        action, _ = model.predict(
            observation,
            deterministic=True
        )

        observation, reward, terminated, truncated, info = eval_env.step(action)

        total_reward += reward
        done = terminated or truncated

    # This must be outside the while loop
    ppo_rewards.append(total_reward)

print("Number of episodes:", len(ppo_rewards))
print("PPO rewards:", ppo_rewards)
print("PPO mean reward:", np.mean(ppo_rewards))

random_mean = -43.808732073026356
ppo_mean = np.mean(ppo_rewards)

improvement = ppo_mean - random_mean

penalty_reduction = (
    (abs(random_mean) - abs(ppo_mean))
    / abs(random_mean)
    * 100
)

print("Random mean:", random_mean)
print("PPO mean:", ppo_mean)
print("Reward improvement:", improvement)
print("Penalty reduction:", penalty_reduction, "%")

print("Random policy:")
print("  Best reward:", np.max(episode_rewards))
print("  Worst reward:", np.min(episode_rewards))
print("  Standard deviation:", np.std(episode_rewards))

print("\nPPO policy:")
print("  Best reward:", np.max(ppo_rewards))
print("  Worst reward:", np.min(ppo_rewards))
print("  Standard deviation:", np.std(ppo_rewards))

results = pd.DataFrame({
    "episode": range(1, 11),
    "random_reward": episode_rewards,
    "ppo_reward": ppo_rewards
})

results["improvement"] = (
    results["ppo_reward"] - results["random_reward"]
)

results.to_csv(
    f"{model_folder}/evaluation_results.csv",
    index=False
)

print(results)

print("\nRandom mean:", results["random_reward"].mean())
print("PPO mean:", results["ppo_reward"].mean())
print("Mean improvement:", results["improvement"].mean())